### ISSUE TITLE
Problema ao ler o OID sobre status da Câmera

### ISSUE THREAD

**Issue by cassiocristo** [diasdmhub/Intelbras_NVR_Zabbix_Template#1]
Ao realizar a coleta de status of remote device o valor recebido sembre e "Empty" mesmo que a câmera esteja "conneted" ou Disable o status smpre coninua o mesmo. 
Inicialmente pensei que era algum problema no meu servidor SNMP, porem testei outras traduções utilizando as minhas MIBS e todas funcionaram, importei também todas as Mibs que o Template module interfaces simples SNMP necessita e mesmo assim o erro snmp_parse_oid(): cannot parse OID "1.3.6.1.4.1.1004849.2.10.2.2.1.3.{#SNMPINDEX}" sempre esse retornado pelo Zabbix. 

o problema é na OID que não esta conseguindo consultar as referencia do VideoLossInfoTable ou o Zabbix que não fraz a tradução correta da OID ?

**Comment by diasdmhub** [comment]
Infelizmente se trata de um bug na MIB do dispositivo, porém, não tenho como confirmar se a falha ocorre em todos NVRs.

Conforme a MIB fornecida pela Intelbras, o objeto “_remoteDeviceStatus_” deveria apresentar outros valores.
```
     remoteDeviceStatus             OBJECT-TYPE
        SYNTAX              DisplayString
        MAX-ACCESS          read-only
        STATUS              current
        DESCRIPTION         "the status ( Connecting, Conneted, Unconnect, Empty, Disable) of  remote device."
        ::=  {  remoteDeviceInfoEntry  3  }
```

Entretanto, o OID “_remoteDeviceStatus_” (1.3.6.1.4.1.1004849.2.10.2.2.1.3.*) sempre apresenta o valor “_empty_” independente do estado real da câmera.

Em junho de 2020 eu solicitei a correção à Intelbras para justamente este status incorreto, mas, infelizmente, a Intelbras não respondeu essa questão até hoje.
Depois de cobrar mais 2x por informações, em setembro de 2021 se limitaram a dizer que estão aguardando informações e retornariam em breve.
Mas até agora nada.

Quanto ao seu erro "snmp_parse_oid()", sugiro que teste a captura de dados com o _snmpget_ ou _snmpwalk_ para confirmar se os dados estão acessíveis.

Na template que disponibilizei, o Zabbix captura os dados diretamente do agente SNMP no dispositivo (NVR) e não há necessidade de importação de MIBs pois são utilizados somente OIDs.

**Comment by cassiocristo** [comment]
Muito obrigado pela atenção, porém muito chato isso da intelbras não ter te dado uma solução, deveria ao menos te dá uma resposta mais concreta. 
Mais veja só eu sou novato em Zabbix mais pensei aqui comigo, será que não dava para ao menos saber se a câmera está respondendo a um ping, já que seu templante consegue capturar o IP dos dispositivos remotos (Câmeras) não teria como criar um protótipo de trigger para retornar um evento  de falha de ping por x tempo ? Isso já ajudaria muito em situações onde o problema é físico no equipamento (câmera) ou na fiação, por exemplo. Só não ira resolver no caso de falha de autenticação ou erro de comunicação ONVIF, por exemplo.

**Comment by diasdmhub** [comment]
Infelizmente as câmeras conectadas diretamente ao NVR não são acessíveis por fora do gravador.
As câmeras no NVR utilizam uma sub-rede distinta mas o gravador não realiza roteamento interno. Portanto, o NVR pode até receber requisições ICMP, mas não consegue respondê-las.
Devido ao software proprietário do gravador, não é possível alterar essa funcionalidade.

Somente é possível monitorar as câmeras individualmente se elas estiverem conectadas por um switch à parte do NVR.

O ideal seria a MIB do NVR responder corretamente pelo status das câmeras, mas, até o momento, dependemos da correção da Intelbras.

**Comment by cassiocristo** [comment]
Certo, muito obrigado pelo esclarecimento, mais eu estava me referindo a coletar o valor chave remoteCam[IpAddr{#SNMPINDEX}] e criar um Trigger utilizando o ICMP para realizar um verificação simples, caso o ping de uma câmera parece a tigger seria acionada, é que eu sou novo em zabbix, esse é meu primeiro projeto ai não sei fazer a expressão para realizar isso, talvez você saiba. 
Outra coisa hoje recebi um retorno da INTELBRAS olha o que ele disseram; 
"
Bom dia Cássio, 

Primeiramente agradecemos o seu contato.

Simulei o funcionamento da OID em questão e foi apresentado o mesmo resultado informado. Abri uma pendência com nosso suporte técnico nível 2 para verificarem o que pode estar ocorrendo.

Por gentileza, informe os dados abaixo para criarmos um contato do senhor em nosso sistema e assim aguardar o retorno do setor responsável:

NOME: 
CPF:
TELEFONE COM DDD: 
CIDADE: 

Ana Paula H.
Analista de Suporte Técnico
Pós Venda
intelbras.com.br

Já mandei os dados, vamos aguardar uma resposta agora, mais se puder manda outro email também cobrando!

**Comment by diasdmhub** [comment]
@cassiocristo , a chave `remoteCam[IpAddr{#SNMPINDEX}]` informa o IP da câmera conforme a configuração de sub-rede PoE registrada no NVR. Este é um dado fornecido pelo próprio NVR, não pela câmera.

Como informei anteriormente, o NVR não realiza roteamento nativamente, portanto, as câmeras ficam praticamente inacessíveis por uma rede externa. Assim, não é possível comunicar o Zabbix com a sub-rede de câmeras do gravador.
Infelizmente, não é possível pingar as câmeras.

A resposta da Intelbras que você recebeu foi similar à primeira resposta que recebi. Se eles te apresentarem uma solução viável, por favor, compartilhe aqui.

**Comment by cassiocristo** [comment]
@diasdmhub muito obrigado pelas explicações qualquer novidade vindo da Intelbras eu posto aqui !
