### ISSUE TITLE
Problema importar template Intelbras_NVR_template_v701.yaml

### ISSUE THREAD

**Issue by lasjsdfs** [diasdmhub/Intelbras_NVR_Zabbix_Template#11]
Estou tendo problemas ao importar o template mais atual, uso o zabbix 7
![Screenshot from 2024-06-21 17-28-23](https://github.com/diasdmhub/Intelbras_NVR_Zabbix_Template/assets/173513259/e79d96d8-0fd1-421e-8339-d759afe511e4)

**Comment by diasdmhub** [comment]
Não tenho certeza, mas esta mensagem de erro parece indicar que a falha é na Dashboard incluída na template.

Esta template é específica para o Zabbix 7.0, no entanto, eu montei alguns ambientes do Zabbix 7 e todos eles importaram a template sem problema.
Infelizmente eu não consegui reproduzir a mesma falha que você.

Você fez alguma alteração no arquivo YAML antes de importar?

Se não, no arquivo YAML da template, por favor, tente alterar os seguintes valores:
- Linha **1752** - de `width: '30'` **para** `width: '24'`
- Linha **1806**- de `width: '30'` **para** `width: '24'`
- Linha **1860** - de `width: '30'` **para** `width: '24'`
- Linha **1931** - de `width: '30'` **para** `width: '24'`

Em seguida, veja se a template é importada corretamente.

**Comment by sorribauru** [comment]
Aproveitando o tópico, poderiam me ajudar a importar o dashboard, por gentileza?

**Comment by lasjsdfs** [comment]
Caro Daniel, descobri a minha falha, eu estava usando o zabbix 7 beta3 e não o rc3. Antes de testar as modificações do template, eu percebi isso, atualizei meu sistema e a importação foi perfeita, obrigado e desculpe o transtorno.

**Comment by diasdmhub** [comment]
Ah que bom que deu certo.
Lembrando que a versão 7.0.0 LTS é a mais recente no momento.

**Comment by lasjsdfs** [comment]
é isso mesmo
[image: Screenshot from 2024-06-25 13-51-22.png]

Em seg., 24 de jun. de 2024 às 16:36, diasdmhub ***@***.***>
escreveu:

**Comment by lasjsdfs** [comment]
olha eu novamente kkkk

No seu template, você tem um item que monitora o status do serviço snmp no
dvr.  Pra mim a trigger dele várias vezes é acionada, porém ele não está
offline, somente o snmp para de responder.
Sabe me dizer a causa ? existe um tempo limite que o dvr corta a
comunicação se tem requisições em demasia ?

Em ter., 25 de jun. de 2024 às 13:52, Juliano Vilela ***@***.***>
escreveu:

**Comment by diasdmhub** [comment]
Juliano, se refere à trigger `No SNMP data collection`?

Por padrão, o item `SNMP Agent Availability` verifica a conectividade SNMP com o dispositivo a cada 3 minutos.

Quanto à trigger `No SNMP data collection`, conforme consta na descrição, ela indica que a conexão SNMP não está disponível por um período. Por padrão, o período é de 5 minutos e ele é definido na macro `{$SNMP.TIMEOUT}`. Isso significa que, se a conexão SNMP do dispositivo não estiver disponível em 5 minutos, ou seja, 2 ciclos do item, a trigger será verdadeira e um evento será gerado.

No seu caso, o alarme é intermitente? Ele se resolve sozinho ou você realiza alguma ação para restaurar a conexão?

Em dispositivos remotos, existem muitos fatores que podem atrapalhar a conexão. Lembrando que o SNMP utiliza **`UDP`**, que pode ser mais problemático.
De qualquer forma, eu sugiro que verifique a conectividade do dispositivo com o seu Zabbix.

Se o evento for intermitente e você achar que ele está muito sensível para o dispositivo, é possível alterar a macro `{$SNMP.TIMEOUT}` para um valor maior e mais adequado. Também é possível criar uma [histerese](https://www.zabbix.com/documentation/7.0/en/manual/config/triggers/expression?hl=hysteresis#hysteresis) na trigger, a fim de evitar a intermitência.

**Comment by lasjsdfs** [comment]
ele se resolve sozinho, vou alterar o tempo pra poder testar

Em qui., 4 de jul. de 2024 às 20:34, diasdmhub ***@***.***>
escreveu:

**Comment by lasjsdfs** [comment]
minha curiosidade maior é, ele falha por problemas na rede ? mas se for,
porque o ping não falha ? ou é o dvr que limita a quantidade de pedidos ?
é mais curiosidade pra saber a origem do problema, valeu por responder

Em qui., 4 de jul. de 2024 às 22:06, Juliano Vilela ***@***.***>
escreveu:

**Comment by diasdmhub** [comment]
O `ICMP` e o `SNMP` são protocolos diferentes e o tratamento deles também pode ser diferente dependendo da rede.

Como disse, existem muitos fatores que podem atrapalhar a conexão. É neste ponto que o Zabbix se destaca, pois ele nos permite identificar falhas como essa.

Seria excelente se gravador tivesse o SO aberto para investigarmos melhor esse tipo de falha, mas, infelizmente, não é assim que a Intelbras e a Dahua trabalham, já que o sistema é fechado.

Então, tente observar o comportamento dos recursos dele (CPU, memória, etc.) nos momentos de desconexão. Talvez isso te dê um indicativo se a falha está no dispositivo.
Se o problema for na rede, tente fazer uma captura de pacotes entre o Zabbix e o gravador. Investigue também se outro fatores externos não estão interferindo na sua rede.

Isso tudo está me parecendo uma questão de rede ou do próprio gravador, independente do Zabbix e a template.

**Comment by lasjsdfs** [comment]
também acredito que seja problema dele, é um 3116 que a intelbras nem dá
suporte mais
ps: com câmeras ips de vários modelos kkkk

Em qui., 4 de jul. de 2024 às 22:54, diasdmhub ***@***.***>
escreveu:
