### ISSUE TITLE
Cameras Showing "Absent Signal" on Dahua NVR (Model: DHI-NVR5232-4KS2)

### ISSUE THREAD

**Issue by ahmad-halabieh** [diasdmhub/Intelbras_NVR_Zabbix_Template#12]
I'm using the Zabbix 7 appliance and experiencing an issue with the Dahua NVR model DHI-NVR5232-4KS2 where all my connected cameras are displaying an "Absent Signal" status. I tested with an SNMP walk, confirmed that .1.3.6.1.4.1.1004849.2.10.2.2.1.3.1 returns an "Empty" response when querying for camera status.

**Comment by diasdmhub** [comment]
I'm not familiar with this "Absent Signal" status.

This template can identify five possible camera status described in Dahua's MIB.
They are converted to numeric values mainly for graphical display, and then mapped to readable names.

- Connecting -> `0`
- Connected -> `1`
- Unconnect -> `2`
- Empty -> `3`
- Disable -> `4`

The status value usually comes from OID `.1.3.6.1.4.1.1004849.2.10.2.2.1.3.INDEX`.

If you "snmpwalk" OID `.1.3.6.1.4.1.1004849.2.10.2.2.1.3`, you should be able to see the status of all cameras.

The `empty` status you see may be related to a known camera bug on Dahua and Intelbras devices.
It was reported in some issues some time ago (see issue #5).

So if you query your device with "snmpwalk" and the response is `empty` for your camera statuses, even though they are connected and accessible, it is most likely the reported bug.

Check if there is a newer firmware version available for your NVR.
