### ISSUE TITLE
Versão em XML

### ISSUE THREAD

**Issue by jefersoncb** [diasdmhub/Intelbras_NVR_Zabbix_Template#2]
Poderia disponibilizar a versão do template também em xml?

**Comment by diasdmhub** [comment]
Segue a última versão da template em XML.
Descompacte o arquivo Zip e importe no seu Zabbix.
Lembrando que este template está na versão 6.0.
Espero que te ajude.
[Intelbras_NVD3116P_template_v2.zip](https://github.com/diasdmhub/Intelbras_NVR_Zabbix_Template/files/8455222/Intelbras_NVD3116P_template_v2.zip)
