### ISSUE TITLE
Sobre os Status das Cameras

### ISSUE THREAD

**Issue by antiqued4** [diasdmhub/Intelbras_NVR_Zabbix_Template#3]
Bom dia e obrigado pela contribuição, sobre os status das cameras, realmente em "empty" não tem muito o que fazer pra esse caso. Então eu resolvi coletar dados sobre os 16 canais analogicos onde eles retornam 0 para offline e 1 para online. Ja as cameras IP, a palhativa foi criar um template de multi-interfaces ICMP, atribuir ao host do DVR, e adicionar os IP das cameras junto.
Entao por hora, apenas a titulo de curiosidade para o Autor e quem quiser usar, essa foi a solução que encontrei. Os 16 canais Analogicos da pra se monitorar, ja as cameras IP a solução foi a citada a cima.

**Comment by diasdmhub** [comment]
Acho que não entendi direito o seu cenário.

Esta template foi criada para preencher um vácuo deixado pelo fabricante Intelbras.
Eu pude validar a template somente em NVRs e não tive a oportunidade de testá-la em DVRs.

Por padrão o NVR com PoE cria uma rede isolada para as câmeras. Geralmente essa rede não é acessível externamente, somente a partir do próprio NVR. Nem mesmo com ICMP.
Presumo que você está utilizando as câmeras IP por meio de um switch distinto do gravador. Sendo assim, elas são acessíveis individualmente.
Neste caso, cada câmera pode ter seu próprio host no Zabbix desde que configurada corretamente com o SNMP ou Simple Check.

Mas me parece que você utiliza um DVR analógico também ou, talvez, híbrido.
Se você conseguiu utilizar a template no (D)HVR, fico bem satisfeito. 

Você poderia informar qual(is) o(s) dispositivo(s) utiliza?

**Comment by CodOfTrade** [comment]
Olá diasdmhub estou tentando monitorar um NVR 1232 mas o status de camera só retorna "emply" conforme a imagem em anexo.. conferi no forum intelbras que esse problema frequente... 
![Capturar](https://user-images.githubusercontent.com/105496588/182871551-7f6029bc-d0d5-48b5-b998-56d70dc98e3d.PNG)

**Comment by diasdmhub** [comment]
@joseDSOliveira , este é um bug conhecido pela Intelbras.
Já relatei esta falha no suporte e no fórum da Intelbras, mas eles não corrigiram.
Eu só pude observar esta falha no NVR "NVD 3116 P", mas acredito que ela ocorre em outros NVR do mesmo período.

Dê uma olhada nos tópicos abaixo do fórum onde já notifiquei esta falha.
Tópico "[SNMP Status do dispositivo remoto - câmera](https://forum.intelbras.com.br/viewtopic.php?f=2138&t=67137)"
Tópico "[Zabbix SNMP Template - NVR Intelbras NVD 3116 P](https://forum.intelbras.com.br/viewtopic.php?f=2138&t=71683)"

**Comment by antiqued4** [comment]
Bom dia meu amigo, entao o seu template, eu testei em alguns DVR
Analogicos, funcionou 100% menos o Status do Canal como esperado, entao eu
resolvi isso com outra OID que pega entre os canal 1 ao 16 se estao
conectados ou não, entao pra parte Analogica Funcionou 100%.
Agora pros DVR que tem analogica ate o canal 16 e cameras ip ate o canal
24, a palhativa foi, criar um template de ICMP pra Multiplas interfaces, ou
seja no mesmo host eu adiciono o IP do DVR normalmente, mas tambem adiciono
as cameras IP, sendo mais de uma interface, nesse caso tambem funcionou
100%, e sim elas estao em um Switch.
Ainda nao testei em NVD conforme voce explicou onde as cameras sao Ligadas
diretamente ao NVD, mas geralmente elas passam por um switch que faz parte
da rede da mesma forma, mas vou tentar.

Em ter., 19 de jul. de 2022 às 21:44, diasdmhub ***@***.***>
escreveu:
