### ISSUE TITLE
Hope, template nao zabbix 6

### ISSUE THREAD

**Issue by paulomokus** [diasdmhub/Intelbras_NVR_Zabbix_Template#4]
Boa noite, não estou conseguindo utilizar o template no zabbix 6, mesmo trocando o titulo de 6.2 para 6, poderia ajudar?

**Comment by diasdmhub** [comment]
Boa tarde, Paulo.
Você poderia descrever qual foi problema encontrado?
Ocorreu algum erro na hora de importar a template?
Poderia descrever os passos que percorreu até o problema?
Você alterou a chave `version` da template para `6.0` (`version: '6.0'`)?

**Comment by paulomokus** [comment]
Fiz o download do arquivo
Editei o arquivo para 6.0 
depois fui importar e deu erro de [Detalhes ](javascript:void(0))Import failed
Tag inválida "/zabbix_export": tag inesperada "template_groups".

**Comment by diasdmhub** [comment]
@paulomokus, após baixar o arquivo *yaml*, altere os valores conforme abaixo:

- Valor da chave `version` de *`6.2`* para **`6.0`**:
  - Linha 2: `  version: 6.0`
<BR>

- Nome da chave *`template_groups`* para **`groups`**:
  - Linha 4: `  groups:`
<BR>

O início do arquivo deve ficar como o exemplo abaixo.
```
zabbix_export:
  version: '6.0'
  date: '2023-01-10T15:45:38Z'
  groups:
```

Após estas alterações, a importação deve funcionar.

**Comment by diasdmhub** [comment]
@paulomokus, atualizei o repositório e agora existem 2 versões: versão 6.0 e versão 6.4

➡️ [Releases](https://github.com/diasdmhub/Intelbras_NVR_Zabbix_Template/releases)

Se você já importou a template na versão anterior, sugiro que exclua a template antiga e importe novamente na nova versão.
Qualquer dúvida, é só chamar.
