### ISSUE TITLE
IP camera status showing status empty 

### ISSUE THREAD

**Issue by sudhakarang** [diasdmhub/Intelbras_NVR_Zabbix_Template#5]
I am using Model : DHI-NVR4232-4KS2 NVR. In SNMP fetach I am able to get ip camera name IP details , but status shows empty .
![zabbix-camera](https://github.com/diasdmhub/Intelbras_NVR_Zabbix_Template/assets/22138949/1ecfd46f-3d18-4e07-acbd-d24c14d51979)

**Comment by diasdmhub** [comment]
This seems similar to issue #1 

Zabbix displays the current camera status based on the device's MIB information.
Therefore, your camera could be absent, faulty, or the NVR's connected device information might be incorrect.
```
        DESCRIPTION         "the status ( Connecting, Conneted, Unconnect, Empty, Disable) of  remote device."
```
The status should be one of the options described above.

It could be a bug in the device's MIB. To check, use a MIB reader and verify the OID `1.3.6.1.4.1.1004849.2.10.2.2.1.3`. 
On the command line, I recommend using Snmpwalk to check if it shows the same value as displayed by Zabbix.

In the past, I encountered a device with this bug. I contacted Intelbras to address the issue, but they were unable to fix it. Instead, they released a new firmware for another device where the bug was resolved.

You might have better luck contacting Dahua support for assistance.

**Comment by sudhakarang** [comment]
Thanks for your update 

Below is the snmpwalk output 

snmpwalk -v 2c -c admin@spa 192.168.168.252 1.3.6.1.4.1.1004849.2.10.2.2.1.3
SNMPv2-SMI::enterprises.1004849.2.10.2.2.1.3.1 = STRING: "Empty"
SNMPv2-SMI::enterprises.1004849.2.10.2.2.1.3.2 = STRING: "Empty"
SNMPv2-SMI::enterprises.1004849.2.10.2.2.1.3.3 = STRING: "Empty"
SNMPv2-SMI::enterprises.1004849.2.10.2.2.1.3.4 = STRING: "Empty"
SNMPv2-SMI::enterprises.1004849.2.10.2.2.1.3.5 = STRING: "Empty"
SNMPv2-SMI::enterprises.1004849.2.10.2.2.1.3.6 = STRING: "Empty"
SNMPv2-SMI::enterprises.1004849.2.10.2.2.1.3.7 = STRING: "Empty"
SNMPv2-SMI::enterprises.1004849.2.10.2.2.1.3.8 = STRING: "Empty"
SNMPv2-SMI::enterprises.1004849.2.10.2.2.1.3.9 = STRING: "Empty"
SNMPv2-SMI::enterprises.1004849.2.10.2.2.1.3.10 = STRING: "Empty"
SNMPv2-SMI::enterprises.1004849.2.10.2.2.1.3.11 = STRING: "Empty"
SNMPv2-SMI::enterprises.1004849.2.10.2.2.1.3.12 = STRING: "Empty"
SNMPv2-SMI::enterprises.1004849.2.10.2.2.1.3.13 = STRING: "Empty"
SNMPv2-SMI::enterprises.1004849.2.10.2.2.1.3.14 = STRING: "Empty"
SNMPv2-SMI::enterprises.1004849.2.10.2.2.1.3.15 = STRING: "Empty"
SNMPv2-SMI::enterprises.1004849.2.10.2.2.1.3.16 = STRING: "Empty"
SNMPv2-SMI::enterprises.1004849.2.10.2.2.1.3.17 = STRING: "Empty"
SNMPv2-SMI::enterprises.1004849.2.10.2.2.1.3.18 = STRING: "Empty"
SNMPv2-SMI::enterprises.1004849.2.10.2.2.1.3.19 = STRING: "Empty"
SNMPv2-SMI::enterprises.1004849.2.10.2.2.1.3.20 = STRING: "Empty"
SNMPv2-SMI::enterprises.1004849.2.10.2.2.1.3.21 = STRING: "Empty"
SNMPv2-SMI::enterprises.1004849.2.10.2.2.1.3.22 = STRING: "Empty"
SNMPv2-SMI::enterprises.1004849.2.10.2.2.1.3.23 = STRING: "Empty"
SNMPv2-SMI::enterprises.1004849.2.10.2.2.1.3.24 = STRING: "Empty"
SNMPv2-SMI::enterprises.1004849.2.10.2.2.1.3.25 = STRING: "Empty"
SNMPv2-SMI::enterprises.1004849.2.10.2.2.1.3.26 = STRING: "Empty"
SNMPv2-SMI::enterprises.1004849.2.10.2.2.1.3.27 = STRING: "Empty"
SNMPv2-SMI::enterprises.1004849.2.10.2.2.1.3.28 = STRING: "Empty"
SNMPv2-SMI::enterprises.1004849.2.10.2.2.1.3.29 = STRING: "Empty"
SNMPv2-SMI::enterprises.1004849.2.10.2.2.1.3.30 = STRING: "Empty"
SNMPv2-SMI::enterprises.1004849.2.10.2.2.1.3.31 = STRING: "Empty"
SNMPv2-SMI::enterprises.1004849.2.10.2.2.1.3.32 = STRING: "Empty"

**Comment by diasdmhub** [comment]
> Thanks for your update
> Below is the snmpwalk output
> (...)

The output you shared indicates that the status of your NVR's connected cameras is "Empty." This could be a potential bug.
Check if there is a newer firmware version available for your NVR.

Additionally, considering the cameras are not directly attached to your NVR, you can try monitoring them separately.
If the cameras are from Dahua, there's a possibility that the template might work for them as well.

**Comment by sudhakarang** [comment]
Yes you are right , I have raised the issue to Dahua support ,  All my cameras are ip based but they don't have snmp , May be the model which I am using does not support the feature .

Thanks for your support @diasdmhub

**Comment by Kosmoplayer** [comment]
Did my research with snmpwalk command and i found those OIDs:
```
NMPv2-SMI::enterprises.1004849.2.10.1.2.1.2.0 = STRING: "Connected"
SNMPv2-SMI::enterprises.1004849.2.10.1.2.1.2.1 = STRING: "Connected"
SNMPv2-SMI::enterprises.1004849.2.10.1.2.1.2.2 = STRING: "Connected"
SNMPv2-SMI::enterprises.1004849.2.10.1.2.1.2.3 = STRING: "Connected"
SNMPv2-SMI::enterprises.1004849.2.10.1.2.1.2.4 = STRING: "Connected"
SNMPv2-SMI::enterprises.1004849.2.10.1.2.1.2.5 = STRING: "Connected"
SNMPv2-SMI::enterprises.1004849.2.10.1.2.1.2.6 = STRING: "Connected"
SNMPv2-SMI::enterprises.1004849.2.10.1.2.1.2.7 = STRING: "Connected"
SNMPv2-SMI::enterprises.1004849.2.10.1.2.1.2.8 = STRING: "Connected"
SNMPv2-SMI::enterprises.1004849.2.10.1.2.1.2.9 = STRING: "Connected"
SNMPv2-SMI::enterprises.1004849.2.10.1.2.1.2.10 = STRING: "Connected"
SNMPv2-SMI::enterprises.1004849.2.10.1.2.1.2.11 = STRING: "Connected"
SNMPv2-SMI::enterprises.1004849.2.10.1.2.1.2.12 = STRING: "Connected"
SNMPv2-SMI::enterprises.1004849.2.10.1.2.1.2.13 = STRING: "Connected"
SNMPv2-SMI::enterprises.1004849.2.10.1.2.1.2.14 = STRING: "Connected"
SNMPv2-SMI::enterprises.1004849.2.10.1.2.1.2.15 = STRING: "Connected"
SNMPv2-SMI::enterprises.1004849.2.10.1.2.1.2.16 = STRING: "Connected"
SNMPv2-SMI::enterprises.1004849.2.10.1.2.1.2.17 = STRING: "Connected"
SNMPv2-SMI::enterprises.1004849.2.10.1.2.1.2.18 = STRING: "Connected"
SNMPv2-SMI::enterprises.1004849.2.10.1.2.1.2.19 = STRING: "Unconnect"
SNMPv2-SMI::enterprises.1004849.2.10.1.2.1.2.20 = STRING: "Connected"
SNMPv2-SMI::enterprises.1004849.2.10.1.2.1.2.21 = STRING: "Unconnect"
SNMPv2-SMI::enterprises.1004849.2.10.1.2.1.2.22 = STRING: "Connected"
SNMPv2-SMI::enterprises.1004849.2.10.1.2.1.2.23 = STRING: "Connected"
SNMPv2-SMI::enterprises.1004849.2.10.1.2.1.2.24 = STRING: "Connected"
SNMPv2-SMI::enterprises.1004849.2.10.1.2.1.2.25 = STRING: "Connected"
SNMPv2-SMI::enterprises.1004849.2.10.1.2.1.2.26 = STRING: "Connected"
SNMPv2-SMI::enterprises.1004849.2.10.1.2.1.2.27 = STRING: "Connected"
SNMPv2-SMI::enterprises.1004849.2.10.1.2.1.2.28 = STRING: "Connected"
SNMPv2-SMI::enterprises.1004849.2.10.1.2.1.2.29 = STRING: "Connected"
SNMPv2-SMI::enterprises.1004849.2.10.1.2.1.2.30 = STRING: "Connected"
SNMPv2-SMI::enterprises.1004849.2.10.1.2.1.2.31 = STRING: "Empty"
```
They shown real status but start from 0 number. Can it be implemented in separate template?

**Comment by diasdmhub** [comment]
Hi @Kosmoplayer.
It is very good to know this information as I have not been able to test many devices. I appreciate your feedback.

Dahua MIB tree for remote devices is usually at `.1.3.6.1.4.1.1004849.2.10`.
Unfortunately, I do not have access to good documentation.
If this tree (**1**) goes to the `...1004849.2.10.1` branch, it seems to be related to **`DVR`** products.
And if this tree (**2**) goes to the `...1004849.2.10.2` branch, it seems to be related to **`NVR`** products.

Despite the similar information, these are different MIB branches.
Testing these 2 branches on an NVR, as you noticed, the index is different.

For branch **1**, I get the following data.
```
$ snmpbulkwalk -t 5 -v 3 -l authPriv -u user -a SHA -A auth -x AES -X crypt -On device.ip 1.3.6.1.4.1.1004849.2.10.1.2.1.2
.1.3.6.1.4.1.1004849.2.10.1.2.1.2.0 = STRING: "Connected"
.1.3.6.1.4.1.1004849.2.10.1.2.1.2.1 = STRING: "Connected"
.1.3.6.1.4.1.1004849.2.10.1.2.1.2.2 = STRING: "Connected"
.1.3.6.1.4.1.1004849.2.10.1.2.1.2.3 = STRING: "Connected"
.1.3.6.1.4.1.1004849.2.10.1.2.1.2.4 = STRING: "Connected"
.1.3.6.1.4.1.1004849.2.10.1.2.1.2.5 = STRING: "Connected"
.1.3.6.1.4.1.1004849.2.10.1.2.1.2.6 = STRING: "Connected"
.1.3.6.1.4.1.1004849.2.10.1.2.1.2.7 = STRING: "Connected"
.1.3.6.1.4.1.1004849.2.10.1.2.1.2.8 = STRING: "Connected"
.1.3.6.1.4.1.1004849.2.10.1.2.1.2.9 = STRING: "Empty"
.1.3.6.1.4.1.1004849.2.10.1.2.1.2.10 = STRING: "Empty"
.1.3.6.1.4.1.1004849.2.10.1.2.1.2.11 = STRING: "Empty"
.1.3.6.1.4.1.1004849.2.10.1.2.1.2.12 = STRING: "Empty"
.1.3.6.1.4.1.1004849.2.10.1.2.1.2.13 = STRING: "Empty"
.1.3.6.1.4.1.1004849.2.10.1.2.1.2.14 = STRING: "Empty"
.1.3.6.1.4.1.1004849.2.10.1.2.1.2.15 = STRING: "Empty"
```

For branch **2**, I get similar data. This time, however, the index starts with `1`.
```
$ snmpbulkwalk -t 5 -v 3 -l authPriv -u user -a SHA -A auth -x AES -X crypt -On device.ip 1.3.6.1.4.1.1004849.2.10.2.2.1.2
.1.3.6.1.4.1.1004849.2.10.2.2.1.3.1 = STRING: "Connected"
.1.3.6.1.4.1.1004849.2.10.2.2.1.3.2 = STRING: "Connected"
.1.3.6.1.4.1.1004849.2.10.2.2.1.3.3 = STRING: "Connected"
.1.3.6.1.4.1.1004849.2.10.2.2.1.3.4 = STRING: "Connected"
.1.3.6.1.4.1.1004849.2.10.2.2.1.3.5 = STRING: "Connected"
.1.3.6.1.4.1.1004849.2.10.2.2.1.3.6 = STRING: "Connected"
.1.3.6.1.4.1.1004849.2.10.2.2.1.3.7 = STRING: "Connected"
.1.3.6.1.4.1.1004849.2.10.2.2.1.3.8 = STRING: "Connected"
.1.3.6.1.4.1.1004849.2.10.2.2.1.3.9 = STRING: "Connected"
.1.3.6.1.4.1.1004849.2.10.2.2.1.3.10 = STRING: "Empty"
.1.3.6.1.4.1.1004849.2.10.2.2.1.3.11 = STRING: "Empty"
.1.3.6.1.4.1.1004849.2.10.2.2.1.3.12 = STRING: "Empty"
.1.3.6.1.4.1.1004849.2.10.2.2.1.3.13 = STRING: "Empty"
.1.3.6.1.4.1.1004849.2.10.2.2.1.3.14 = STRING: "Empty"
.1.3.6.1.4.1.1004849.2.10.2.2.1.3.15 = STRING: "Empty"
.1.3.6.1.4.1.1004849.2.10.2.2.1.3.16 = STRING: "Empty"
```

So, this template works for many **D**VRs, but it is focused on **N**VRs, so I'll keep it as is.

You could create a new discovery rule for such a branch (1). All you need to do is clone the items associated with that discovery and customize the OID.

**Comment by antoniusgenta** [comment]
Hi @diasdmhub can you share Grafana template NVR grafana_dash_nvd_3316. thx

**Comment by diasdmhub** [comment]
Hi @antoniusgenta. Unfortunately, I do not have a Grafana template to share.
I can only recommend that you connect your Zabbix to Grafana and try to plot your own device metrics.

If it helps, [here's a simple export](https://github.com/diasdmhub/Intelbras_NVR_Zabbix_Template/raw/refs/heads/main/images/grafana_dashboard_sample.json) of the Grafana dashboard that is shown on the images in this template.
However, it is not customized for public sharing and may require changes to the data-source `uid`, group filter and hostname. Also, this dashboard displays a number of cameras and SLA metrics that are specific to a particular environment.

**Comment by Aleksei5771** [comment]
From DHI-NVR4116-4KS2/L:
iso.3.6.1.4.1.1004849.2.10.1.2.1.2.0 = STRING: "Connected"
iso.3.6.1.4.1.1004849.2.10.1.2.1.2.1 = STRING: "Connected"
iso.3.6.1.4.1.1004849.2.10.1.2.1.2.2 = STRING: "Connected"
iso.3.6.1.4.1.1004849.2.10.1.2.1.2.3 = STRING: "Connected"
iso.3.6.1.4.1.1004849.2.10.1.2.1.2.4 = STRING: "Connected"
iso.3.6.1.4.1.1004849.2.10.1.2.1.2.5 = STRING: "Connected"
iso.3.6.1.4.1.1004849.2.10.1.2.1.2.6 = STRING: "Connected"
iso.3.6.1.4.1.1004849.2.10.1.2.1.2.7 = STRING: "Connected"
iso.3.6.1.4.1.1004849.2.10.1.2.1.2.8 = STRING: "Connected"
iso.3.6.1.4.1.1004849.2.10.1.2.1.2.9 = STRING: "Connected"
iso.3.6.1.4.1.1004849.2.10.1.2.1.2.10 = STRING: "Empty"
iso.3.6.1.4.1.1004849.2.10.1.2.1.2.11 = STRING: "Empty"
iso.3.6.1.4.1.1004849.2.10.1.2.1.2.12 = STRING: "Empty"
iso.3.6.1.4.1.1004849.2.10.1.2.1.2.13 = STRING: "Empty"
iso.3.6.1.4.1.1004849.2.10.1.2.1.2.14 = STRING: "Empty"
iso.3.6.1.4.1.1004849.2.10.1.2.1.2.15 = STRING: "Empty"
