### ISSUE TITLE
Camera status empty

### ISSUE THREAD

**Issue by GambaRota** [diasdmhub/Intelbras_NVR_Zabbix_Template#7]
I'm using the model with a Dahua NVR DHI-NVR608-32-4KS2
I have a problem with the status of the cameras. They are connected but I always get the status empty.
IP and name are OK

I specified the password in the MACRO {$API_PASS}.
Have you already encountered this problem?
Sincerely
![Empty](https://github.com/diasdmhub/Intelbras_NVR_Zabbix_Template/assets/155469231/1c360a5e-1fb5-46ba-8508-41a96424fa3c)

**Comment by rpalmeiro** [comment]
Hi,

I´m using a Intelbras iNVD7032 and have the same scenario.

I always get the status empty for cameras, but IP and Name are OK.

Running SNMP Walk:

02/01/2024 17:38:44 (2870 ms) : 1.3.6.1.4.1.1004849.2.10.2.2.1.2.26 = "192.168.3.207" [ASN_OCTET_STR]
02/01/2024 17:38:44 (2886 ms) : 1.3.6.1.4.1.1004849.2.10.2.2.1.2.27 = "192.168.3.182" [ASN_OCTET_STR]
02/01/2024 17:38:44 (2904 ms) : 1.3.6.1.4.1.1004849.2.10.2.2.1.2.28 = "192.168.3.75" [ASN_OCTET_STR]
02/01/2024 17:38:44 (2921 ms) : 1.3.6.1.4.1.1004849.2.10.2.2.1.2.29 = "192.168.0.0" [ASN_OCTET_STR]
02/01/2024 17:38:44 (2942 ms) : 1.3.6.1.4.1.1004849.2.10.2.2.1.2.30 = "192.168.3.77" [ASN_OCTET_STR]
02/01/2024 17:38:44 (2965 ms) : 1.3.6.1.4.1.1004849.2.10.2.2.1.2.31 = "192.168.3.78" [ASN_OCTET_STR]
02/01/2024 17:38:44 (2987 ms) : 1.3.6.1.4.1.1004849.2.10.2.2.1.2.32 = "192.168.3.76" [ASN_OCTET_STR]

**02/01/2024 17:38:44 (3004 ms) : 1.3.6.1.4.1.1004849.2.10.2.2.1.3.1 = "Empty" [ASN_OCTET_STR]
02/01/2024 17:38:44 (3021 ms) : 1.3.6.1.4.1.1004849.2.10.2.2.1.3.2 = "Empty" [ASN_OCTET_STR]
02/01/2024 17:38:44 (3041 ms) : 1.3.6.1.4.1.1004849.2.10.2.2.1.3.3 = "Empty" [ASN_OCTET_STR]
02/01/2024 17:38:44 (3061 ms) : 1.3.6.1.4.1.1004849.2.10.2.2.1.3.4 = "Empty" [ASN_OCTET_STR]
02/01/2024 17:38:44 (3083 ms) : 1.3.6.1.4.1.1004849.2.10.2.2.1.3.5 = "Empty" [ASN_OCTET_STR]
02/01/2024 17:38:44 (3104 ms) : 1.3.6.1.4.1.1004849.2.10.2.2.1.3.6 = "Empty" [ASN_OCTET_STR]
02/01/2024 17:38:44 (3122 ms) : 1.3.6.1.4.1.1004849.2.10.2.2.1.3.7 = "Empty" [ASN_OCTET_STR]
02/01/2024 17:38:44 (3142 ms) : 1.3.6.1.4.1.1004849.2.10.2.2.1.3.8 = "Empty" [ASN_OCTET_STR]
02/01/2024 17:38:44 (3159 ms) : 1.3.6.1.4.1.1004849.2.10.2.2.1.3.9 = "Empty" [ASN_OCTET_STR]
02/01/2024 17:38:44 (3182 ms) : 1.3.6.1.4.1.1004849.2.10.2.2.1.3.10 = "Empty" [ASN_OCTET_STR]
02/01/2024 17:38:44 (3204 ms) : 1.3.6.1.4.1.1004849.2.10.2.2.1.3.11 = "Empty" [ASN_OCTET_STR]
02/01/2024 17:38:44 (3242 ms) : 1.3.6.1.4.1.1004849.2.10.2.2.1.3.12 = "Empty" [ASN_OCTET_STR]
02/01/2024 17:38:44 (3260 ms) : 1.3.6.1.4.1.1004849.2.10.2.2.1.3.13 = "Empty" [ASN_OCTET_STR]
02/01/2024 17:38:44 (3283 ms) : 1.3.6.1.4.1.1004849.2.10.2.2.1.3.14 = "Empty" [ASN_OCTET_STR]
02/01/2024 17:38:44 (3303 ms) : 1.3.6.1.4.1.1004849.2.10.2.2.1.3.15 = "Empty" [ASN_OCTET_STR]
02/01/2024 17:38:44 (3322 ms) : 1.3.6.1.4.1.1004849.2.10.2.2.1.3.16 = "Empty" [ASN_OCTET_STR]
02/01/2024 17:38:44 (3339 ms) : 1.3.6.1.4.1.1004849.2.10.2.2.1.3.17 = "Empty" [ASN_OCTET_STR]
02/01/2024 17:38:44 (3361 ms) : 1.3.6.1.4.1.1004849.2.10.2.2.1.3.18 = "Empty" [ASN_OCTET_STR]
02/01/2024 17:38:44 (3383 ms) : 1.3.6.1.4.1.1004849.2.10.2.2.1.3.19 = "Empty" [ASN_OCTET_STR]
02/01/2024 17:38:44 (3401 ms) : 1.3.6.1.4.1.1004849.2.10.2.2.1.3.20 = "Empty" [ASN_OCTET_STR]
02/01/2024 17:38:44 (3428 ms) : 1.3.6.1.4.1.1004849.2.10.2.2.1.3.21 = "Empty" [ASN_OCTET_STR]
02/01/2024 17:38:44 (3449 ms) : 1.3.6.1.4.1.1004849.2.10.2.2.1.3.22 = "Empty" [ASN_OCTET_STR]
02/01/2024 17:38:44 (3468 ms) : 1.3.6.1.4.1.1004849.2.10.2.2.1.3.23 = "Empty" [ASN_OCTET_STR]
02/01/2024 17:38:44 (3490 ms) : 1.3.6.1.4.1.1004849.2.10.2.2.1.3.24 = "Empty" [ASN_OCTET_STR]
02/01/2024 17:38:44 (3509 ms) : 1.3.6.1.4.1.1004849.2.10.2.2.1.3.25 = "Empty" [ASN_OCTET_STR]
02/01/2024 17:38:44 (3529 ms) : 1.3.6.1.4.1.1004849.2.10.2.2.1.3.26 = "Empty" [ASN_OCTET_STR]
02/01/2024 17:38:44 (3549 ms) : 1.3.6.1.4.1.1004849.2.10.2.2.1.3.27 = "Empty" [ASN_OCTET_STR]
02/01/2024 17:38:44 (3573 ms) : 1.3.6.1.4.1.1004849.2.10.2.2.1.3.28 = "Empty" [ASN_OCTET_STR]
02/01/2024 17:38:44 (3593 ms) : 1.3.6.1.4.1.1004849.2.10.2.2.1.3.29 = "Empty" [ASN_OCTET_STR]
02/01/2024 17:38:44 (3615 ms) : 1.3.6.1.4.1.1004849.2.10.2.2.1.3.30 = "Empty" [ASN_OCTET_STR]
02/01/2024 17:38:44 (3633 ms) : 1.3.6.1.4.1.1004849.2.10.2.2.1.3.31 = "Empty" [ASN_OCTET_STR]
02/01/2024 17:38:44 (3663 ms) : 1.3.6.1.4.1.1004849.2.10.2.2.1.3.32 = "Empty" [ASN_OCTET_STR]**

02/01/2024 17:38:44 (3684 ms) : 1.3.6.1.4.1.1004849.2.10.2.2.1.4.1 = "143 POTE PERIM" [ASN_OCTET_STR]
02/01/2024 17:38:44 (3704 ms) : 1.3.6.1.4.1.1004849.2.10.2.2.1.4.2 = "142 POTE PERIM CX" [ASN_OCTET_STR]
02/01/2024 17:38:44 (3723 ms) : 1.3.6.1.4.1.1004849.2.10.2.2.1.4.3 = "141 POTE PERIM" [ASN_OCTET_STR]
02/01/2024 17:38:44 (3741 ms) : 1.3.6.1.4.1.1004849.2.10.2.2.1.4.4 = "144 POTE FINAL" [ASN_OCTET_STR]
02/01/2024 17:38:44 (3815 ms) : 1.3.6.1.4.1.1004849.2.10.2.2.1.4.5 = "145 POTE FINAL" [ASN_OCTET_STR]
02/01/2024 17:38:44 (3834 ms) : 1.3.6.1.4.1.1004849.2.10.2.2.1.4.6 = "146 POTE" [ASN_OCTET_STR]

**Comment by diasdmhub** [comment]
The `{$API_PASS}` macro is available for possible actions and future monitoring items.
Issue #6 has a very specific example of such use, mainly as a temporary resolution for a specific device bug.
Unless you create actions that use the device's API, the macro will not be used on any item.

Your camera status problem is very similar to issues #1, #3 and #5.
It may be a bug in the device's MIB as the `remoteDeviceStatus` object (`1.3.6.1.4.1.1004849.2.10.2.2.1.3.*`) should return different values. However, it always shows the `empty` value despite the camera's real status.
```
remoteDeviceStatus             OBJECT-TYPE
   SYNTAX              DisplayString
   MAX-ACCESS          read-only
   STATUS              current
   DESCRIPTION         "the status ( Connecting, Conneted, Unconnect, Empty, Disable) of  remote device."
   ::=  {  remoteDeviceInfoEntry  3  }
```

You can confirm these values outside of Zabbix by running an SNMP "_walk_" with `snmpwalk`.

For an Intelbras NVR, I was able to open a support ticket and escalate it for an RMA.

Zabbix just reads the value from the recorder.
So, I would suggest you to open a support request with the manufacturer or distributor.

**Comment by diasdmhub** [comment]
Please refer to issue #5 for new comments.
