### ISSUE TITLE
Erro ao tentar adicionar o template NVD 3116p

### ISSUE THREAD

**Issue by rodrigonx3** [diasdmhub/Intelbras_NVR_Zabbix_Template#8]
![image](https://github.com/diasdmhub/Intelbras_NVR_Zabbix_Template/assets/104142646/a7bc8d06-f8e7-4345-a182-150d42d6f53a)

Ao tentar adicionar este templeta aparece o erro como na imagem, como resolvo?

**Comment by diasdmhub** [comment]
As versões mais recentes da template estão informadas nos badges do topo da descrição do README.
Você pode baixá-las na [**página de releases**](https://github.com/diasdmhub/Intelbras_NVR_Zabbix_Template/releases).

Olhando somente para a imagem, é difícil identificar a causa da falha.
`Interface {#IFDESCR}: Network traffic` é um protótipo de gráfico disponível no item de descoberta de rede (`Network interfaces discovery`).
Esse gráfico é utilizado na dashboard padrão `NVR Dashboard`.
Infelizmente, eu não pude reproduzir a mesma falha por aqui.

Por favor, peço que detalhe um pouco mais o seu cenário.
Qual é a versão do seu Zabbix e qual é a versão da template que baixou?
Houve alguma alteração no arquivo `yaml` da template?

**Comment by rodrigonx3** [comment]
Bom dia, 
Zabbix 6.4.10
Template [Intelbras_NVD3116P_template_v3.yaml](https://github.com/diasdmhub/Intelbras_NVR_Zabbix_Template/blob/main/Template/Intelbras_NVD3116P_template_v3.yaml)
Nao  houve nenhuma alteração no arquivo, simplesmente tentei importalo.

**Comment by rodrigonx3** [comment]
Fiz um teste e eliminei esta parte do codigo onde referenciava o erro, 
![image](https://github.com/diasdmhub/Intelbras_NVR_Zabbix_Template/assets/104142646/07452fbd-eef2-437e-92fe-c43b8c86c396)
Funcionou perfeitamente, so que agora que consegui usar o template, foi gerado outro erro.
Ao verificar as cameras, elas todas estao online e conectada no NVR, mas no template os dados de todas as cameras estao retornando EMPTY, quando deveriam retornar Connected.
![image](https://github.com/diasdmhub/Intelbras_NVR_Zabbix_Template/assets/104142646/35a6e30d-4db3-467c-af40-76548dc51646)

![image](https://github.com/diasdmhub/Intelbras_NVR_Zabbix_Template/assets/104142646/94d42d8c-8ff6-4536-a715-0754f97249c8)

Mandei ai a versao do meu NVR
E o retorno do discovery com as cameras aparecendo EMPTY
Como posso resolver?

**Comment by rodrigonx3** [comment]
Por favor desconsidere, testei com outro NVR e retornou corretamente. Muito obrigado.

**Comment by rodrigonx3** [comment]
Por favor desconsidere, testei com outro NVR e retornou corretamente. Muito obrigado.

**Comment by diasdmhub** [comment]
Fico feliz que tenha resolvido o problema.
Provavelmente o erro ocorreu porque você está utilizando uma versão antiga da template com o Zabbix mais recente.

Ressalto que, para o Zabbix 6.4, a versão mais recente da template é `647` e está disponível na página de releases.

Quanto ao valor `empty` das câmeras, é um dado que vem do próprio gravador. Trata-se de um bug na plataforma da Dahua/Intelbras e já foi comentado nas issues #1, #3, #5 e #7.
